name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t salemhamdani/flask-app:${{ github.sha }} .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push salemhamdani/flask-app:${{ github.sha }}
 # Step 3: Update Deployment in GitHub
    - name: Update Deployment Manifest
      run: |
        sed -i "s|image: salemhamdani/flask-app:.*|image: salemhamdani/flask-app:${{ github.sha }}|g" Deployment.yaml
        git config --global user.email "salemhamdani09@gmail.com"
        git config --global user.name "salemhamdani"
        git add Deployment.yaml
        git commit -m "Update Deployment to use image ${{ github.sha }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}